[package]
name = "clipl"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
description = "ClipLinux command-line interface"
publish.workspace = true

[[bin]]
name = "clipl"
path = "src/main.rs"

[dependencies]
clipl-core.workspace = true
clipl-platform.workspace = true
clipl-protocol.workspace = true
clap.workspace = true
serde_json.workspace = true
serde.workspace = true

[lints]
workspace = true
